version: '3'

tasks:
  client:dev:
    dir: 'client'
    cmds:
      - npm run dev

  client:lint:
    dir: 'client'
    cmds:
      - npm run typecheck
      - npm run lint

  server:dev:
    dir: 'server'
    cmds:
      - cargo watch -x run

  server:test:
    env:
      FIRESTORE_EMULATOR_HOST: 127.0.0.1:10000
    cmds:
      - cargo llvm-cov nextest --html --all --no-fail-fast

  server:lint:
    dir: 'server'
    cmds:
      - cargo check
      - cargo clippy

  server:fmt:
    dir: 'server'
    cmds:
      - cargo fmt

  server:doc:
    dir: 'server'
    cmds:
      - cargo doc
